### ISSUE TITLE
Unable to use my own images

### ISSUE THREAD

**Issue by mikeprecious** [awt2542/ImageFiller#1]
Followed instructions for using custom images. Using Apple Mac App Store purchased copy of Sketch app. Unable to successfully execute custom image placement in my Sketch doc. Seeking some help with this.
![screen shot 2015-03-31 at 8 39 03 pm](https://cloud.githubusercontent.com/assets/1815165/6932379/7f0b01b6-d7e6-11e4-8a2b-350efdb16a56.png)

**Comment by awt2542** [comment]
Yeah, you probably have to allow Sketch to access the folder you've referred to in your plugin. Is that what it's asking for?

**Comment by mikeprecious** [comment]
Tried downloaded-license-keyed version of Sketch - same problem as with Mac App Store version. My custom plugin and photos will not work in Sketch. However, the default plugins such as Architecture, Animals do work. All I did was duplicate the Architecture plugin and modify the subfolder text. I then created a folder in the Photos folder, tossed in my image files. Won't work. Am I missing something?
![screen shot 2015-04-01 at 9 45 59 pm](https://cloud.githubusercontent.com/assets/1815165/6956212/8422dc00-d8b8-11e4-8834-07ec5408b9be.png)
![screen shot 2015-04-01 at 9 45 49 pm](https://cloud.githubusercontent.com/assets/1815165/6956213/842c758a-d8b8-11e4-92ad-8666bf11bec8.png)

**Comment by mikeprecious** [comment]
Hi Andreas,

here is the plugin package I’m working with. Could you let me know if I’m omitting something in my script? Or if the script is correct? 

Thanks!
Mike

**Comment by awt2542** [comment]
Your screenshot looks right to me. Did you try to attach some files? Seems to be missing. Can you give it another try?

**Comment by mikeprecious** [comment]
I did try to attach a zipped up ImageFiller plugin package with my customized plugin and images for you to review. Link to it here: https://www.dropbox.com/s/0lvsfj72fcoks3f/ImageFiller.zip?dl=0 I modelled my custom plugin off the architecture plugin variant, simply changing the image path reference point, and creating the reference point folder. It will not work. Can you have a look at the plugin I created and validate if it's correct? Thanks!

**Comment by awt2542** [comment]
Hi! Think I found the problem. Your string is not properly formatted. The character after ...myphotos/ should be an ", instead of “ (subtle difference, there). Fix that and it should work :)
